apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch-exporter
  namespace: graylog
  labels:
    app: elasticsearch-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch-exporter
  template:
    metadata:
      labels:
        app: elasticsearch-exporter
    spec:
      containers:
      - name: elasticsearch-exporter
        image: /elasticsearch-exporter:v1.3.0
        command: 
          - '--es.uri=http://elasticsearch-data.graylog.svc.cluster.local`'
      tolerations:
              #      - key: node.kubernetes.io/not-ready
              #        effect: NoExecute
              #        tolerationSeconds: 0
              #      - key: node.kubernetes.io/unreachable
              #        effect: NoExecute
              #        tolerationSeconds: 0
      - key: app
        effect: NoSchedule
        operator: Equal 
        value: elk
      - key: app
        effect: NoExecute
        operator: Equal 
        value: elk
      imagePullSecrets:
        - name: -repo

