apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: elasticsearch-master
    env: prod
  name: elasticsearch-master
  namespace: graylog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch-master
  template:
    metadata:
      labels:
        app: elasticsearch-master
        env: prod
    spec:
      containers:
      - name: elasticsearch-master
        image: elasticsearch:7.17.0
        env:
                #        - name: discovery.seed_hosts
                #          value: elasticsearch-ingest,elasticsearch-data,elasticsaerch-master
                #        - name: cluster.initial_master_nodes
                #          value: elasticsearch-master
                #        - name: node.name
                #          valueFrom:
                #            fieldRef:
                #              apiVersion: v1
                #              fieldPath: metadata.name
                #        - name: cluster.name
                #          value: graylog
                #        - name: node.data
                #          value: "false"
                #        - name: node.master
                #          value: "true"
                #        - name: node.ingest
                #          value: "false"
                #        - name: network.host
                #          value: "0.0.0.0"
        - name: bootstrap.memory_lock
          value: "false"
        - name: TZ
          value: 'Asia/Tehran'
          #        - name: ES_JAVA_OPTS
          #          value: "-Xms${ES_HEAP_SIZE:-12g} -Xmx${ES_HEAP_SIZE:-12g}"
        volumeMounts:
        - name: storage-master
          mountPath: /usr/share/elasticsearch/data
          #        - name: elasticsearch-master-jvm
          #          mountPath: /usr/share/elasticsearch/config/jvm.options
          #          subPath: jvm.options
        - name: elasticsearch-config-master
          mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
          subPath: elasticsearch.yml

        ports:
        - containerPort: 9300
          name: transport
          protocol: TCP
        resources:
          limits:
            cpu: "3"
            memory: 8Gi

      initContainers:
      - name: init-sysctl
        image: /busybox
        command: ['sysctl', '-w', 'vm.max_map_count=262144']
        securityContext:
          privileged: true

      - name: fix-the-volume-permission
        image: /busybox
        command: ['sh', '-c', 'chown -R 1000:1000 /usr/share/elasticsearch/data']
        securityContext:
          privileged: true
        volumeMounts:
          - name: storage-master
            mountPath: /usr/share/elasticsearch/data

      - name: increase-the-ulimit
        image: /busybox
        command: ['sh', '-c', 'ulimit -n 65536']
        securityContext:
          privileged: true

      volumes:
      - name: storage-master
        persistentVolumeClaim:
          claimName: elasticsearch-master-pvc
      - name: elasticsearch-config-master
        configMap:
          name: elasticsearch-config-master


      tolerations:
              #      - key: node.kubernetes.io/not-ready
              #        effect: NoExecute
              #        tolerationSeconds: 0
              #      - key: node.kubernetes.io/unreachable
              #        effect: NoExecute
              #        tolerationSeconds: 0
      - key: app
        effect: NoSchedule
        operator: Equal 
        value: elk
      - key: app
        effect: NoExecute
        operator: Equal 
        value: elk
      imagePullSecrets:
        - name: -repo

      imagePullSecrets:
        - name: -repo
---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: elasticsearch-ingest
    env: prod
  name: elasticsearch-ingest
  namespace: graylog
spec:
  selector:
    matchLabels:
      app: elasticsearch-ingest
      env: prod
  template:
    metadata:
      labels:
        app: elasticsearch-ingest
        env: prod
    spec:
      containers:
      - name: elasticsearch-ingest
        image: elasticsearch:7.17.0
        env:
                #        - name: discovery.seed_hosts
                #          value: elasticsearch-ingest,elasticsearch-data,elasticsaerch-master
                #        - name: cluster.initial_master_nodes
                #          value: elasticsearch-master
                #        - name: node.name
                #          value: elasticsearch-ingest
                #        - name: cluster.name
                #          value: graylog
                #        - name: node.data
                #          value: "false"
                #        - name: node.master
                #          value: "false"
                #        - name: node.ingest
                #          value: "true"
        - name: network.host
          value: "0.0.0.0"
        - name: bootstrap.memory_lock
          value: "false"
        - name: TZ
          value: 'Asia/Tehran'
          #        - name: ES_JAVA_OPTS
          #          value: "-Xms${ES_HEAP_SIZE:-12g} -Xmx${ES_HEAP_SIZE:-12g}"
        ports:
        - containerPort: 9300
          name: transport
          protocol: TCP
          #        resources:
          #          limits:
          #            cpu: "3"
          #            memory: 16Gi
        
        volumeMounts:
        - name: storage-ingest
          mountPath: /usr/share/elasticsearch/data
        - name: elasticsearch-config-ingest
          mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
          subPath: elasticsearch.yml
          #        - name: elasticsearch-ingest-jvm
          #          mountPath: /usr/share/elasticsearch/config/jvm.options
          #          subPath: jvm.options

      initContainers:
      - name: init-sysctl
        image: /busybox
        command: ['sysctl', '-w', 'vm.max_map_count=262144']
        securityContext:
          privileged: true

      - name: fix-the-volume-permission
        image: /busybox
        command: ['sh', '-c', 'chown -R 1000:1000 /usr/share/elasticsearch/data']
        securityContext:
          privileged: true
        volumeMounts:
          - name: storage-ingest
            mountPath: /usr/share/elasticsearch/data

      - name: increase-the-ulimit
        image: /busybox
        command: ['sh', '-c', 'ulimit -n 65536']
        securityContext:
          privileged: true

      volumes:
      - name: storage-ingest
        persistentVolumeClaim:
          claimName: elasticsearch-clinet-pvc
      - name: elasticsearch-config-ingest
        configMap:
          name: elasticsearch-config-ingest
          #      - name: elasticsearch-ingest-jvm
          #        configMap:
          #          name: elasticsearch-ingest-jvm

      tolerations:
              #      - key: node.kubernetes.io/not-ready
              #        effect: NoExecute
              #        tolerationSeconds: 0
              #      - key: node.kubernetes.io/unreachable
              #        effect: NoExecute
              #        tolerationSeconds: 0
      - key: app
        effect: NoSchedule
        operator: Equal 
        value: elk
      - key: app
        effect: NoExecute
        operator: Equal 
        value: elk

      imagePullSecrets:
        - name: -repo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: elasticsearch-data
    env: prod
  name: elasticsearch-data
  namespace: graylog
spec:
  selector:
    matchLabels:
      app: elasticsearch-data
      env: prod
  template:
    metadata:
      labels:
        app: elasticsearch-data
        env: prod
    spec:
      containers:
      - name: elasticsearch-data
        image: elasticsearch:7.17.0
        env:
                #        - name: discovery.seed_hosts
                #          value: elasticsearch-master,elasticsearch-data
                #        - name: cluster.initial_master_nodes
                #          value: elasticsearch-master,elasticsearch-data,elasticsearch-ingest
                #        - name: node.name
                #          value: elasticsearch-data
                #        - name: cluster.name
                #          value: graylog
                #        - name: node.data
                #          value: "true"
                #        - name: node.master
                #          value: "false"
                #        - name: node.ingest
                #          value: "false"
        - name: network.host
          value: "0.0.0.0"
        - name: bootstrap.memory_lock
          value: "false"
        - name: TZ
          value: 'Asia/Tehran'
          #        - name: ES_JAVA_OPTS
          #          value: "-Xms${ES_HEAP_SIZE:-12g} -Xmx${ES_HEAP_SIZE:-12g}"
        ports:
        - containerPort: 9300
          name: transport
          protocol: TCP
          #        resources:
          #          limits:
          #            cpu: "3"
          #            memory: 16Gi
          #
        volumeMounts:
        - name: storage-data
          mountPath: /usr/share/elasticsearch/data
        - name: elasticsearch-config-data
          mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
          subPath: elasticsearch.yml
          #        - name: elasticsearch-ingest-jvm
          #          mountPath: /usr/share/elasticsearch/config/jvm.options
          #          subPath: jvm.options

      initContainers:
      - name: init-sysctl
        image: /busybox
        command: ['sysctl', '-w', 'vm.max_map_count=262144']
        securityContext:
          privileged: true

      - name: fix-the-volume-permission
        image: /busybox
        command: ['sh', '-c', 'chown -R 1000:1000 /usr/share/elasticsearch/data']
        securityContext:
          privileged: true
        volumeMounts:
          - name: storage-data
            mountPath: /usr/share/elasticsearch/data

      - name: increase-the-ulimit
        image: /busybox
        command: ['sh', '-c', 'ulimit -n 65536']
        securityContext:
          privileged: true

      volumes:
      - name: storage-data
        persistentVolumeClaim:
          claimName: elasticsearch-data-pvc
      - name: elasticsearch-config-data
        configMap:
          name: elasticsearch-config-data
          #      - name: elasticsearch-ingest-jvm
          #        configMap:
          #          name: elasticsearch-ingest-jvm

      tolerations:
              #      - key: node.kubernetes.io/not-ready
              #        effect: NoExecute
              #        tolerationSeconds: 0
              #      - key: node.kubernetes.io/unreachable
              #        effect: NoExecute
              #        tolerationSeconds: 0
      - key: app
        effect: NoSchedule
        operator: Equal 
        value: elk
      - key: app
        effect: NoExecute
        operator: Equal 
        value: elk
      imagePullSecrets:
        - name: -repo

      imagePullSecrets:
        - name: -repo
---
apiVersion: v1
kind: Service
metadata:
  namespace: graylog
  name: elasticsearch-data
  labels:
    env: prod
spec:
  type: ClusterIP
  selector:
    app: elasticsearch-data
  ports:
  - name: http
    port: 9200
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  namespace: graylog
  name: elasticsearch-ingest
  labels:
    env: prod
spec:
  type: ClusterIP
  selector:
    app: elasticsearch-ingest
  ports:
  - name: http
    port: 9200
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  namespace: graylog
  name: elasticsearch-master
  labels:
    env: prod
spec:
  clusterIP: None
  selector:
    app: elasticsearch-master
  ports:
  - name: transport
    port: 9300
