apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-storage-es-cluster-0
  #  labels:
  #app: elasticsearch
spec:
  storageClassName: standard
  capacity:
    storage: 10Gi 
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.112.90
    path: /nfs/SSD-1TB/graylog/elasticsearch/es-cluster-1
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - "192.168.112.87"
          - "192.168.112.88"
          - "192.168.112.89"

            #---
            #apiVersion: v1
            #kind: PersistentVolume
            #metadata:
            #  name: elasticsearch-storage-es-cluster-1
            #spec:
            #  storageClassName: standard
            #  capacity:
            #    storage: 10Gi 
            #  accessModes:
            #    - ReadWriteMany
            #  persistentVolumeReclaimPolicy: Retain
            #  nfs:
            #    server: 192.168.112.90
            #    path: /nfs/SSD-1TB/graylog/elasticsearch/es-cluster-1
            #  nodeAffinity:
            #    required:
            #      nodeSelectorTerms:
            #      - matchExpressions:
            #        - key: kubernetes.io/hostname
            #          operator: In
            #          values:
            #          - 192.168.112.87
            #          - 192.168.112.88
            #          - 192.168.112.89
            #---
            #apiVersion: v1
            #kind: PersistentVolume
            #metadata:
            #  name: elasticsearch-storage-es-cluster-2
            #spec:
            #  storageClassName: standard
            #  capacity:
            #    storage: 10Gi 
            #  accessModes:
            #    - ReadWriteMany
            #  persistentVolumeReclaimPolicy: Retain
            #  nfs:
            #    server: 192.168.112.90
            #    path: /nfs/SSD-1TB/graylog/elasticsearch/es-cluster-2
            #  nodeAffinity:
            #    required:
            #      nodeSelectorTerms:
            #      - matchExpressions:
            #        - key: kubernetes.io/hostname
            #          operator: In
            #          values:
            #          - 192.168.112.87
            #          - 192.168.112.88
            #          - 192.168.112.89
