apiVersion: v1
kind: PersistentVolume
metadata:
  name: graylog-pv
  namespace: graylog
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 
    path: /nfs/SSD-1TB/graylog/graylog
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: graylog-pvc
  namespace: graylog
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  volumeName: graylog-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: graylog-plugin-pv
  namespace: graylog
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 
    path: /nfs/SSD-1TB/graylog/plugin
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: graylog-plugin-pvc
  namespace: graylog
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeName: graylog-plugin-pv
