apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: graylog
  labels:
    app: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
      - name: kibana
        image: kibana:7.17.0
        env:
          - name: ELASTICSEARCH_HOSTS
            value: http://elasticsearch-ingest:9200
          - name: TZ
            value: 'Asia/Tehran'

      tolerations:
              #      - key: node.kubernetes.io/not-ready
              #        effect: NoExecute
              #        tolerationSeconds: 0
              #      - key: node.kubernetes.io/unreachable
              #        effect: NoExecute
              #        tolerationSeconds: 0
      - key: app
        effect: NoSchedule
        operator: Equal 
        value: elk
      - key: app
        effect: NoExecute
        operator: Equal 
        value: elk
      imagePullSecrets:
        - name: -repo

---
apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: graylog
  labels:
    app: kibana
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5601
  selector:
    app: kibana
