apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-config
  namespace: graylog
data:
  logstash.yml: |
    http.host: "0.0.0.0"
    path.config: /usr/share/logstash/pipeline
  logstash.conf: |
    input {
       beats {
         port => 9000
        }
     }

     output {
             if  [fields][app] =~ "customerclub-prod" {
             elasticsearch { 
               hosts => ["http://elasticsearch-ingest:9200"]
               index => "customerclub-192.168.112.59-%{[@metadata][version]}-%{+YYYY.MM.dd}"
           }
         }
             if  [fields][app] =~ "cms-prod" {
             elasticsearch { 
               hosts => ["http://elasticsearch-ingest:9200"]
               index => "cms-192.168.112.43-%{[@metadata][version]}-%{+YYYY.MM.dd}"
           }
         }
       }
