apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-config
  namespace: graylog
data:
  logstash.yml: |
    http.host: "0.0.0.0"
    path.config: /usr/share/logstash/pipeline
  logstash.conf: |
    input {
       tcp {
         type => "gelf"
         port => 9000
         #codec => plain {charset=>"US-ASCII"}
         }


            #        gelf {
            #          port => "9000"
            #          type => docker
            #              }

    } 
 
     output {
             if  "gelf" in [type] {
             elasticsearch {
               hosts => ["http://elasticsearch-ingest:9200"]
               index => "customerclub-%{[@metadata][version]}-%{+YYYY.MM.dd}"
           }
            
         }
       }
