apiVersion: v1
kind: ConfigMap
metadata:
  name: club-config
  namespace: graylog
data:
   club.conf: |
      input {
        beats {
          port => 9000
          }
       }
      output {
        elasticsearch {
           hosts => ["elasticsearch-ingest:9200"]
           index => "club-%{[@metadata][version]}-%{+YYYY.MM.dd}"
          }
      }
