apiVersion: v1
kind: PersistentVolume
metadata:
  name: logstash-pv
  namespace: graylog
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 
    path: /nfs/SSD-1TB/graylog/logstash
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logstash-pvc
  namespace: graylog
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: logstash-pv
