apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-config
  namespace: graylog
data:
  logstash.yml: |
    http.host: "0.0.0.0"
    path.config: /usr/share/logstash/pipeline
  logstash.conf: |
    input {
      jdbc {
        jdbc_driver_library => "/usr/share/logstash/logstash-core/lib/jars/mysql-connector-java-8.0.17.jar"
        jdbc_driver_class => "com.mysql.cj.jdbc.Driver"
        jdbc_connection_string => "jdbc:mysql://${DB_HOST}:3306/${DB_DATABASE}?useTimezone=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Tehran"
        jdbc_user => "${DB_USERNAME}"
        jdbc_password => "${DB_PASSWORD}"
        statement => "select id, user_id, bol_number, bol_datetime, status, receiver_company_identity, sender_company_identity, cargo_identity,
                        cargo_name, load_status_label, load_status, first_driver_national_code, second_driver_national_code, car_tag,
                        sender_code, receiver_code, sender_loading_postal_code, receiver_discharge_postal_code, beneficiary_identity,
                        company_identity, discharge_datetime, sender_company_name, bol_serial_number, cargo_name_received, updated_at
                        from bill_of_ladings
                        where updated_at > DATE_SUB(:sql_last_value, INTERVAL 2 MINUTE)"
        use_column_value => true
        tracking_column => "updated_at"
        tracking_column_type => "timestamp"
        schedule => "* * * * *"
        last_run_metadata_path => "/etc/logstash/conf.d/lastrun/.logstash_jdbc_last_run"
      }
    }
    output {
       elasticsearch {
            hosts => ["elasticsearch-ingest:9200"]
            index => "paybaar-road"
            document_id => "%{id}"
            }
    }
    
