apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-config
  namespace: graylog
data:
  logstash.yml: |
    http.host: "0.0.0.0"
    path.config: /usr/share/logstash/pipeline
  logstash.conf: |
    input {
      beats {
        port => 9000
        }
     }
    
    output {
      elasticsearch {
         hosts => ["elasticsearch-ingest:9200"]
         index => "customerclub-%{[@metadata][version]}-%{+YYYY.MM.dd}"
        }
    }
