apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb0-graylog-pv
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi 
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.112.90
    path: /mnt/SSD-1TB/graylog/mongodb/mongodb0
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb1-graylog-pv
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.112.90
    path: /mnt/SSD-1TB/graylog/mongodb/mongodb1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb2-graylog-pv
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.112.90
    path: /mnt/SSD-1TB/graylog/mongodb/mongodb2
