apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb0-pv
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi 
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 
    path: /nfs/SSD-1TB/graylog/mongodb/mongodb0
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb1-pv
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 
    path: /nfs/SSD-1TB/graylog/mongodb/mongodb1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb2-pv
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 
    path: /nfs/SSD-1TB/graylog/mongodb/mongodb2
